export type Gender = 'men' | 'women' | 'unisex';
export type Color = { name: string; hex: string };

export type Product = {
  slug: string;
  sku: string;
  name: string;
  category: Category;
  gender: Gender;
  price: number;
  colors: Color[];
  sizes: string[];
  soldOut?: string[];
  material: Material;
  composition: string;
  origin: string;
  images: string[];
  texture: 'dark' | 'light';
  description: string;
  details: string[];
  care: string[];
  isNew?: boolean;
  limited?: boolean;
  /** menor = mais vendido */
  rank: number;
  /** maior = mais recente */
  drop: number;
};

export const CATEGORIES = ['Outerwear', 'Knitwear', 'Tailoring', 'Shirts', 'Essentials', 'Bottom'] as const;
export type Category = (typeof CATEGORIES)[number];

export const MATERIALS = ['Lã', 'Cashmere', 'Merino', 'Algodão', 'Linho', 'Viscose'] as const;
export type Material = (typeof MATERIALS)[number];

export const SIZES = ['PP', 'P', 'M', 'G', 'GG'] as const;

const C = {
  black: { name: 'Preto', hex: '#0b0b0a' },
  graphite: { name: 'Grafite', hex: '#3a3936' },
  offwhite: { name: 'Off-white', hex: '#efece4' },
  sand: { name: 'Areia', hex: '#cdbfa9' },
  camel: { name: 'Camel', hex: '#a57d55' },
  heather: { name: 'Cinza mescla', hex: '#9a9893' },
  ivory: { name: 'Marfim', hex: '#e8e1d3' },
  stone: { name: 'Pedra', hex: '#b4ab9d' },
  lead: { name: 'Chumbo', hex: '#55565a' },
  mist: { name: 'Azul névoa', hex: '#9aa4ad' },
} satisfies Record<string, Color>;

const P = (n: string, count = 2) => Array.from({ length: count }, (_, i) => `/images/p/${n}-${i + 1}.webp`);

const careWool = ['Lavagem a seco profissional', 'Não usar alvejante', 'Passar a vapor pelo avesso', 'Guardar em cabide largo, protegido por capa de algodão'];
const careKnit = ['Lavar à mão em água fria com sabão neutro', 'Secar na horizontal, à sombra', 'Não torcer', 'Guardar dobrado'];
const careCotton = ['Lavar à máquina a 30 °C, pelo avesso', 'Não usar secadora', 'Passar em temperatura média'];

export const products: Product[] = [
  {
    slug: 'structured-jacket',
    sku: 'NM-FW26-001',
    name: 'NOMA Structured Jacket',
    category: 'Outerwear',
    gender: 'men',
    price: 1290,
    colors: [C.black, C.graphite],
    sizes: [...SIZES],
    soldOut: ['PP'],
    material: 'Algodão',
    composition: '72% algodão encerado, 28% poliamida · forro 100% cupro',
    origin: 'Confeccionada em São Paulo com sarja encerada de tecelagem italiana.',
    images: P('structured-jacket'),
    texture: 'dark',
    description: 'Jaqueta de ombros estruturados e comprimento na cintura. A sarja encerada ganha pátina com o uso e mantém a forma sem entretela pesada.',
    details: ['Modelagem regular, ombro levemente construído', 'Zíper frontal oculto em metal escovado', 'Dois bolsos com vivo e um bolso interno', 'Punho com pesponto duplo'],
    care: careCotton,
    isNew: true,
    rank: 2,
    drop: 16,
  },
  {
    slug: 'essential-tee',
    sku: 'NM-ES-002',
    name: 'NOMA Essential Tee',
    category: 'Essentials',
    gender: 'unisex',
    price: 349,
    colors: [C.offwhite, C.black, C.sand],
    sizes: [...SIZES],
    material: 'Algodão',
    composition: '100% algodão Pima, malha 240 g/m²',
    origin: 'Algodão Pima peruano, tecido e costurado no Brasil.',
    images: P('essential-tee', 3),
    texture: 'light',
    description: 'A camiseta que sustenta o guarda-roupa. Malha encorpada de 240 g/m², gola canelada que não deforma e caimento reto que funciona sozinho ou sob alfaiataria.',
    details: ['Modelagem reta, levemente ampla no ombro', 'Gola canelada de 2 cm com fita interna', 'Costuras laterais eliminadas: corpo tubular', 'Pré-lavada: não encolhe'],
    care: careCotton,
    isNew: true,
    rank: 1,
    drop: 15,
  },
  {
    slug: 'tailored-trouser',
    sku: 'NM-FW26-003',
    name: 'NOMA Tailored Trouser',
    category: 'Bottom',
    gender: 'men',
    price: 790,
    colors: [C.sand, C.black, C.graphite],
    sizes: [...SIZES],
    soldOut: ['GG'],
    material: 'Lã',
    composition: '98% lã fria, 2% elastano',
    origin: 'Lã fria Super 110s de tecelagem em Biella, Itália.',
    images: P('tailored-trouser'),
    texture: 'light',
    description: 'Calça de alfaiataria com uma prega frontal e perna reta. Lã fria que respira no calor e mantém o vinco ao longo do dia.',
    details: ['Cintura média com ajuste lateral', 'Prega frontal única', 'Barra italiana de 3,5 cm', 'Bolsos faca e traseiros com botão'],
    care: careWool,
    isNew: true,
    rank: 4,
    drop: 14,
  },
  {
    slug: 'oversized-knit',
    sku: 'NM-FW26-004',
    name: 'NOMA Oversized Knit',
    category: 'Knitwear',
    gender: 'women',
    price: 890,
    colors: [C.black, C.heather, C.ivory],
    sizes: ['P', 'M', 'G'],
    material: 'Merino',
    composition: '80% lã merino extrafina, 20% cashmere',
    origin: 'Fio italiano, tricotado em máquina retilínea no Sul de Minas.',
    images: P('oversized-knit'),
    texture: 'dark',
    description: 'Tricô de volume generoso, ombro caído e mangas longas que se acumulam no punho. Merino extrafino com toque de cashmere: macio, sem pinicar.',
    details: ['Modelagem ampla, ombro deslocado', 'Ponto meia em calibre 7', 'Punho e barra em ribana 2×2', 'Peso: 540 g'],
    care: careKnit,
    isNew: true,
    rank: 3,
    drop: 13,
  },
  {
    slug: 'noire-signature-coat',
    sku: 'NM-FW26-005',
    name: 'Noiré Signature Coat',
    category: 'Outerwear',
    gender: 'women',
    price: 2490,
    colors: [C.black, C.camel],
    sizes: ['PP', 'P', 'M', 'G'],
    material: 'Lã',
    composition: '90% lã virgem, 10% cashmere · dupla face, sem forro',
    origin: 'Lã virgem de Biella, Itália. Acabamento manual em ateliê próprio em São Paulo.',
    images: [...P('noire-coat'), '/images/e/texture-dark.webp'],
    texture: 'dark',
    description: 'O casaco que abre a coleção FW26. Lã dupla face trabalhada à mão, sem forro e sem entretela: a estrutura vem do próprio tecido.',
    details: ['Abotoamento duplo com quatro botões em metal escovado', 'Lapela entalhada larga, moldada a vapor', 'Bolsos embutidos com acabamento invisível', 'Costuras abertas à mão, 18 horas de ateliê por peça'],
    care: careWool,
    isNew: true,
    limited: true,
    rank: 5,
    drop: 17,
  },
  {
    slug: 'camel-overcoat',
    sku: 'NM-FW26-006',
    name: 'Camel Wool Overcoat',
    category: 'Outerwear',
    gender: 'men',
    price: 1890,
    colors: [C.camel, C.black],
    sizes: [...SIZES],
    material: 'Lã',
    composition: '80% lã, 20% poliamida · forro 100% viscose',
    origin: 'Tecido de lã penteada de tecelagem portuguesa.',
    images: P('camel-overcoat'),
    texture: 'light',
    description: 'Sobretudo de corte reto e comprimento abaixo do joelho. Veste sobre tricô ou alfaiataria sem apertar nos ombros.',
    details: ['Abotoamento simples com três botões de chifre', 'Lapela entalhada', 'Fenda traseira central', 'Comprimento: 108 cm no tamanho M'],
    care: careWool,
    rank: 7,
    drop: 10,
  },
  {
    slug: 'crew-knit',
    sku: 'NM-FW26-007',
    name: 'Chunky Crew Knit',
    category: 'Knitwear',
    gender: 'men',
    price: 820,
    colors: [C.offwhite, C.heather],
    sizes: [...SIZES],
    material: 'Lã',
    composition: '100% lã britânica',
    origin: 'Fio britânico, tricotado no Sul de Minas.',
    images: P('crew-knit'),
    texture: 'light',
    description: 'Gola careca em ponto inglês, com textura que aparece de perto. Aquece sem volume excessivo.',
    details: ['Modelagem regular', 'Ponto inglês em calibre 5', 'Gola, punho e barra em ribana', 'Peso: 690 g'],
    care: careKnit,
    rank: 9,
    drop: 9,
  },
  {
    slug: 'heavy-long-sleeve',
    sku: 'NM-ES-008',
    name: 'Heavy Long Sleeve',
    category: 'Essentials',
    gender: 'men',
    price: 429,
    colors: [C.black, C.offwhite],
    sizes: [...SIZES],
    material: 'Algodão',
    composition: '100% algodão orgânico, malha 280 g/m²',
    origin: 'Algodão orgânico certificado, produzido no Brasil.',
    images: P('long-sleeve'),
    texture: 'dark',
    description: 'Manga longa de malha pesada, com punho canelado e caimento firme. Substitui o suéter nos dias amenos.',
    details: ['Modelagem regular', 'Gola canelada de 2,5 cm', 'Punho canelado longo', 'Pré-lavada'],
    care: careCotton,
    rank: 6,
    drop: 8,
  },
  {
    slug: 'double-trench',
    sku: 'NM-FW26-009',
    name: 'Double Trench',
    category: 'Outerwear',
    gender: 'men',
    price: 1690,
    colors: [C.stone, C.black],
    sizes: ['P', 'M', 'G', 'GG'],
    material: 'Algodão',
    composition: '100% gabardine de algodão, tratamento repelente',
    origin: 'Gabardine japonesa, confeccionada em São Paulo.',
    images: P('double-trench'),
    texture: 'light',
    description: 'Trench coat de abotoamento duplo em gabardine compacta. Repele garoa e ganha caimento mais macio com o tempo.',
    details: ['Abotoamento duplo', 'Cinto removível com fivela forrada', 'Pala nas costas', 'Punhos com presilha'],
    care: careWool,
    isNew: true,
    rank: 10,
    drop: 12,
  },
  {
    slug: 'linen-camp-shirt',
    sku: 'NM-ES-010',
    name: 'Linen Camp Shirt',
    category: 'Shirts',
    gender: 'men',
    price: 520,
    colors: [C.mist, C.ivory],
    sizes: [...SIZES],
    material: 'Linho',
    composition: '100% linho europeu lavado',
    origin: 'Linho europeu certificado, costurado no Brasil.',
    images: P('linen-shirt', 3),
    texture: 'light',
    description: 'Camisa de gola aberta e mangas curtas em linho lavado. Amassa do jeito certo.',
    details: ['Modelagem reta, barra para usar por fora', 'Gola camp', 'Botões de madrepérola', 'Pala dupla'],
    care: ['Lavar à máquina em ciclo delicado a 30 °C', 'Secar à sombra', 'Passar úmida, se desejar'],
    rank: 8,
    drop: 7,
  },
  {
    slug: 'silence-trench',
    sku: 'NM-FW26-011',
    name: 'Silence Trench',
    category: 'Outerwear',
    gender: 'women',
    price: 1790,
    colors: [C.black],
    sizes: ['PP', 'P', 'M', 'G'],
    material: 'Viscose',
    composition: '64% viscose, 36% poliéster reciclado · acabamento acetinado',
    origin: 'Tecido japonês de toque seco, confeccionado em São Paulo.',
    images: P('silence-trench'),
    texture: 'dark',
    description: 'Peça central da Silence Collection. Trench longo com volume nas costas e cinto que marca sem apertar.',
    details: ['Comprimento midi', 'Prega macho nas costas', 'Cinto e passantes', 'Manga raglã'],
    care: careWool,
    isNew: true,
    limited: true,
    rank: 11,
    drop: 11,
  },
  {
    slug: 'grey-wool-coat',
    sku: 'NM-FW26-012',
    name: 'Grey Wool Coat',
    category: 'Outerwear',
    gender: 'women',
    price: 1590,
    colors: [C.heather, C.graphite],
    sizes: ['PP', 'P', 'M', 'G'],
    soldOut: ['M'],
    material: 'Lã',
    composition: '70% lã, 30% poliamida',
    origin: 'Tecido de lã penteada de tecelagem portuguesa.',
    images: P('grey-coat'),
    texture: 'light',
    description: 'Casaco reto em lã mescla, comprimento no quadril. Veste como blazer, aquece como casaco.',
    details: ['Abotoamento simples', 'Ombro natural', 'Bolsos com lapela', 'Forro em cupro'],
    care: careWool,
    rank: 12,
    drop: 6,
  },
  {
    slug: 'wide-tailored-trouser',
    sku: 'NM-FW26-013',
    name: 'Wide Tailored Trouser',
    category: 'Bottom',
    gender: 'women',
    price: 820,
    colors: [C.ivory, C.black],
    sizes: ['PP', 'P', 'M', 'G'],
    material: 'Lã',
    composition: '96% lã fria, 4% elastano',
    origin: 'Lã fria de Biella, Itália.',
    images: P('wide-trouser'),
    texture: 'light',
    description: 'Cintura alta, pernas amplas e comprimento que toca o chão com salto. Movimento em cada passo.',
    details: ['Cintura alta com passantes', 'Duas pregas frontais', 'Barra sem acabamento aparente', 'Bolsos faca profundos'],
    care: careWool,
    rank: 13,
    drop: 5,
  },
  {
    slug: 'merino-turtleneck',
    sku: 'NM-ES-014',
    name: 'Merino Turtleneck',
    category: 'Knitwear',
    gender: 'women',
    price: 590,
    colors: [C.black, C.ivory, C.sand],
    sizes: [...SIZES],
    material: 'Merino',
    composition: '100% lã merino extrafina 17,5 mícrons',
    origin: 'Merino australiano, tricotado no Brasil.',
    images: P('merino-turtleneck'),
    texture: 'dark',
    description: 'Gola alta em merino fino, justo sem marcar. A primeira camada de qualquer look de inverno.',
    details: ['Modelagem ajustada', 'Gola dupla dobrável', 'Calibre 14', 'Peso: 260 g'],
    care: careKnit,
    rank: 14,
    drop: 4,
  },
  {
    slug: 'tailored-blazer',
    sku: 'NM-FW26-015',
    name: 'Tailored Blazer',
    category: 'Tailoring',
    gender: 'women',
    price: 1390,
    colors: [C.black, C.lead],
    sizes: ['PP', 'P', 'M', 'G'],
    material: 'Lã',
    composition: '100% lã fria · forro 100% cupro',
    origin: 'Lã fria de Biella, alfaiataria em São Paulo.',
    images: P('tailored-blazer'),
    texture: 'dark',
    description: 'Blazer de ombro marcado e cintura levemente acinturada. Construção meio-canvas, que molda com o corpo.',
    details: ['Construção meio-canvas', 'Lapela entalhada', 'Abotoamento simples, um botão', 'Fendas laterais'],
    care: careWool,
    isNew: true,
    rank: 15,
    drop: 3,
  },
  {
    slug: 'ivory-suit-blazer',
    sku: 'NM-FW26-016',
    name: 'Ivory Suit Blazer',
    category: 'Tailoring',
    gender: 'women',
    price: 1450,
    colors: [C.ivory, C.sand],
    sizes: ['PP', 'P', 'M', 'G'],
    material: 'Linho',
    composition: '55% linho, 45% viscose',
    origin: 'Linho italiano, alfaiataria em São Paulo.',
    images: P('ivory-blazer'),
    texture: 'light',
    description: 'Blazer cropped em linho marfim, com ombros definidos e manga levemente longa. Compõe conjunto com a Wide Tailored Trouser.',
    details: ['Comprimento cropped', 'Lapela pontiaguda', 'Sem forro', 'Botão forrado'],
    care: careWool,
    rank: 16,
    drop: 2,
  },
];

export const bySlug = (slug: string) => products.find((p) => p.slug === slug);

export const newArrivals = ['structured-jacket', 'essential-tee', 'tailored-trouser', 'oversized-knit'].map((s) => bySlug(s)!);

export type Collection = { slug: string; title: string; eyebrow: string; intro: string; image: string; filter: (p: Product) => boolean };

export const collections: Collection[] = [
  {
    slug: 'new',
    title: 'New Collection',
    eyebrow: 'FW26',
    intro: 'Formas amplas, lã dupla face e uma paleta que não passa do cinza.',
    image: '/images/e/look-2.webp',
    filter: (p) => !!p.isNew,
  },
  {
    slug: 'masculino',
    title: "Men's Collection",
    eyebrow: 'Masculino',
    intro: 'Alfaiataria descomplicada, malhas pesadas e casacos que duram décadas.',
    image: '/images/e/cat-men.webp',
    filter: (p) => p.gender !== 'women',
  },
  {
    slug: 'feminino',
    title: "Women's Collection",
    eyebrow: 'Feminino',
    intro: 'Volume, fluidez e estrutura, em peças que atravessam estações.',
    image: '/images/e/cat-women.webp',
    filter: (p) => p.gender !== 'men',
  },
  {
    slug: 'essentials',
    title: 'Essentials',
    eyebrow: 'Sempre disponíveis',
    intro: 'A base. Malhas, camisas e tricôs refinados até o último ponto.',
    image: '/images/e/cat-essentials.webp',
    filter: (p) => p.category === 'Essentials' || p.category === 'Shirts' || (p.category === 'Knitwear' && p.price < 700),
  },
];

export const collectionBySlug = (slug: string) => collections.find((c) => c.slug === slug);

export function related(p: Product, n = 4) {
  const pool = products.filter((x) => x.slug !== p.slug && (x.gender === p.gender || x.gender === 'unisex' || p.gender === 'unisex'));
  const other = pool.filter((x) => x.category !== p.category);
  return [...other, ...pool.filter((x) => x.category === p.category)].slice(0, n);
}
