// Fluxo de compra ponta a ponta. uso: node tools/flow.mjs <outdir> [width=1440] [height=900]
import puppeteer from 'puppeteer-core';
const [out, w = '1440', h = '900'] = process.argv.slice(2);
const mobile = +w < 768;
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new' });
const p = await b.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
p.on('console', (m) => m.type() === 'error' && errs.push('console: ' + m.text()));
await p.setViewport({ width: +w, height: +h, isMobile: mobile, hasTouch: mobile });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const shot = (n) => p.screenshot({ path: `${out}/${n}.png` });
const clickText = async (sel, text) => {
  const ok = await p.evaluate((sel, text) => {
    const el = [...document.querySelectorAll(sel)].find((e) => e.textContent.trim().toLowerCase().includes(text.toLowerCase()) && e.offsetParent !== null);
    if (el) el.click();
    return !!el;
  }, sel, text);
  if (!ok) throw new Error(`não achei ${sel} "${text}"`);
};
const typeIn = async (label, value) => {
  const id = await p.evaluate((label) => {
    const l = [...document.querySelectorAll('label')].find((l) => l.textContent.trim().toLowerCase().startsWith(label.toLowerCase()) && l.offsetParent !== null);
    return l?.getAttribute('for') || l?.querySelector('input')?.id;
  }, label);
  if (!id) throw new Error('campo ' + label);
  await p.type(`[id="${id}"]`, value, { delay: 8 });
};

await p.goto('http://localhost:3012/produto/noire-signature-coat', { waitUntil: 'networkidle0', timeout: 180000 });
await wait(2500);
await clickText('button', 'Adicionar à sacola');
await wait(900);
await shot('01-size-error');
await p.click('[role=radiogroup][aria-label=Tamanho] button:nth-child(3)');
await clickText('button', 'Adicionar à sacola');
await wait(1400);
await shot('02-drawer');
await p.keyboard.press('Escape');
await wait(700);
await p.goto('http://localhost:3012/produto/essential-tee', { waitUntil: 'networkidle0' });
await wait(1500);
await p.click('[role=radiogroup][aria-label=Tamanho] button:nth-child(2)');
await clickText('button', 'Adicionar à sacola');
await wait(1400);
await shot('03-drawer-2');
await clickText('button', 'Finalizar compra');
await p.waitForNavigation({ waitUntil: 'networkidle0' }).catch(() => {});
await wait(1500);
await clickText('button', 'Continuar para entrega');
await wait(600);
await shot('04-step1-errors');
await typeIn('E-mail', 'ana.teste@noma.store');
await typeIn('Nome completo', 'Ana Teste Silva');
await typeIn('CPF', '52998224725');
await typeIn('Celular', '11987654321');
await shot('05-step1');
await clickText('button', 'Continuar para entrega');
await wait(1000);
await typeIn('CEP', '01310100');
await wait(2500);
await typeIn('Número', '1578');
await shot('06-step2');
await clickText('button', 'Continuar para pagamento');
await wait(1000);
await clickText('label', 'Cartão de crédito');
await wait(600);
await typeIn('Número do cartão', '4242424242424242');
await typeIn('Nome impresso', 'ana teste');
await typeIn('Validade', '1230');
await typeIn('CVV', '123');
await wait(400);
await shot('07-step3-card');
await clickText('label', 'PIX');
await wait(600);
await clickText('button', 'Finalizar pedido');
await wait(2800);
await shot('08-confirm');
console.log(errs.join('\n') || 'no errors');
await b.close();
