// Captura estados de UI: mega menu, busca, filtros, menu mobile, lupa.
import puppeteer from 'puppeteer-core';
const [out] = process.argv.slice(2);
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new' });
const errs = [];
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const page = async (w, h) => { const p = await b.newPage(); p.on('pageerror', (e) => errs.push(e.message)); p.on('console', (m) => m.type() === 'error' && errs.push(m.text())); await p.setViewport({ width: w, height: h, isMobile: w < 768, hasTouch: w < 768 }); return p; };
let p = await page(1440, 900);
await p.goto('http://localhost:3012/colecao/new', { waitUntil: 'networkidle0', timeout: 180000 });
await wait(2000);
const nav = await p.$$('nav[aria-label=Principal] a');
await nav[2].hover(); await wait(900);
await p.screenshot({ path: `${out}/ui-mega.png` });
await p.mouse.move(700, 800); await wait(600);
await p.click('button[aria-label=Buscar]'); await wait(800);
await p.keyboard.type('casaco', { delay: 30 }); await wait(700);
await p.screenshot({ path: `${out}/ui-search.png` });
await p.keyboard.press('Escape'); await wait(700);
await p.evaluate(() => [...document.querySelectorAll('button')].find((b) => b.textContent.trim().startsWith('Filtros')).click()); await wait(900);
await p.evaluate(() => [...document.querySelectorAll('[role=dialog] button')].find((b) => b.textContent.trim() === 'M').click()); await wait(400);
await p.screenshot({ path: `${out}/ui-filters.png` });
await p.keyboard.press('Escape'); await wait(600);
await p.goto('http://localhost:3012/', { waitUntil: 'networkidle0' }); await wait(1500);
const top = await p.evaluate(() => { const el = document.getElementById('sig-title').closest('section'); return el.getBoundingClientRect().top + scrollY; });
await p.evaluate((y) => window.scrollTo(0, y), top + 60); await wait(1800);
const box = await p.evaluate(() => { const r = document.querySelector('#sig-title').closest('section').querySelector('[class*="aspect-[2/3]"]').getBoundingClientRect(); return { x: r.left, y: r.top, w: r.width, h: r.height }; });
await p.mouse.move(box.x + box.w * 0.34, box.y + box.h * 0.62, { steps: 5 }); await wait(700);
await p.screenshot({ path: `${out}/ui-loupe.png` });
await p.evaluate(() => window.scrollTo(0, 0)); await wait(600);
const cat = await p.evaluate(() => { const r = document.querySelector('a[href="/colecao/feminino"].group').getBoundingClientRect(); return { x: r.left + r.width / 2, y: r.top + scrollY }; });
await p.evaluate((y) => window.scrollTo(0, y - 100), cat.y); await wait(1500);
await p.mouse.move(cat.x, 300); await wait(1400);
await p.screenshot({ path: `${out}/ui-cats.png` });
p = await page(390, 844);
await p.goto('http://localhost:3012/', { waitUntil: 'networkidle0' }); await wait(1500);
await p.click('button[aria-label="Abrir menu"]'); await wait(1300);
await p.screenshot({ path: `${out}/ui-mmenu.png` });
console.log(errs.join('\n') || 'no errors');
await b.close();
